# Generated by Django 5.1.1 on 2024-09-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dateOfCreation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
